services:
#    notification.example:
#        class: NotificationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.xprience_repository:
        class: AppBundle\Infrastructure\Persistence\Doctrine\DoctrineExperienceRepository
        arguments: 
            - "@doctrine.orm.entity_manager"  

    app.add_experience:
        class: AppBundle\Application\UseCase\Experience\CreateXpRequest

    app.xprience_service:
        class: AppBundle\Application\UseCase\Experience\CreateXpService
